#!/usr/bin/perl

use strict;
use warnings;
use Voronota qw(calculate_contacts);

my $coords = [];
while( <> ) {
    my @line = split /\s+/, $_;
    push @$coords, ( $line[0] + 0.0, $line[1] + 0.0, $line[2] + 0.0, 0 );
}

my $contacts = calculate_contacts( $coords );
local $, = ' ';
local $\ = "\n";
foreach (@$contacts) {
    print $_->{first}, $_->{second}, $_->{area};
}
